name: Generate Sitemap

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://www.montgomerynx.com
          drop-html-extension: true
          exclude-paths: 404.html

      - name: Commit sitemap
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
          # Check for changes before committing
          if git diff --quiet sitemap.xml; then
            echo "No changes in sitemap.xml, skipping commit."
          else
            git add sitemap.xml
            git commit -m "Update sitemap"
            git push origin HEAD:main
          fi
